import { MorphIcon } from 'morphicons/react'
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Brain,
  Calendar,
  Cat,
  Check,
  ChevronDown,
  Clock,
  Copy,
  Crown,
  Download,
  Eye,
  FileImage,
  FileText,
  Flame,
  Folder,
  FolderOpen,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  Maximize,
  Menu,
  MessageSquare,
  Monitor,
  MoreHorizontal,
  Music,
  Pencil,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Scissors,
  Search,
  Send,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  Video,
  Volume2,
  Wallet,
  Wand2,
  X,
  LayoutTemplate,
  LayoutGrid,
} from 'lucide'

const MAP = {
  picture: Image,
  image: Image,
  video: Video,
  play: Play,
  pause: Pause,
  search: Search,
  cat: Cat,
  brain: Brain,
  magic: Sparkles,
  sparkle: Sparkles,
  wand: Wand2,
  refresh: RefreshCw,
  reload: RefreshCw,
  download: Download,
  upload: Upload,
  close: X,
  x: X,
  lock: Lock,
  link: Link,
  folder: Folder,
  folderOpen: FolderOpen,
  imageFiles: FileImage,
  images: FileImage,
  fileText: FileText,
  right: ArrowRight,
  arrowRight: ArrowRight,
  left: ArrowLeft,
  arrowLeft: ArrowLeft,
  up: ChevronDown,
  down: ChevronDown,
  delete: Trash2,
  trash: Trash2,
  check: Check,
  time: Clock,
  clock: Clock,
  home: Home,
  edit: Pencil,
  music: Music,
  target: Target,
  scissors: Scissors,
  info: Info,
  attention: AlertTriangle,
  alert: AlertCircle,
  walletOne: Wallet,
  wallet: Wallet,
  trend: TrendingUp,
  fire: Flame,
  shoppingCart: ShoppingCart,
  view: Eye,
  monitor: Monitor,
  crown: Crown,
  calendar: Calendar,
  adjustment: SlidersHorizontal,
  inbox: Inbox,
  filter: SlidersHorizontal,
  send: Send,
  plus: Plus,
  message: MessageSquare,
  copy: Copy,
  more: MoreHorizontal,
  volume: Volume2,
  fullscreen: Maximize,
  setting: Settings,
  settings: Settings,
  logout: LogOut,
  list: List,
  history: History,
  menu: Menu,
  template: LayoutTemplate,
  layoutGrid: LayoutGrid,
}

export default function Icon({
  name,
  size = 16,
  theme,
  fill,
  strokeWidth = 2,
  style,
  className,
}) {
  const icon = MAP[name]
  if (!icon) {
    // graceful fallback: render a small circle placeholder
    return (
      <span
        className={className}
        style={{
          display: 'inline-flex',
          width: size,
          height: size,
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: '50%',
          background: 'currentColor',
          opacity: 0.35,
          ...style,
        }}
      />
    )
  }
  return (
    <MorphIcon
      icon={icon}
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={{ display: 'inline-block', verticalAlign: 'middle', ...style }}
    />
  )
}
